### ISSUE TITLE
L09 - 10/23/2024

### ISSUE THREAD

**Issue by evansturmey** [ausbennett/mes-finance-platform#30]
**Topic**
VnV Plan

**Date and Time**
10/23/2024

**Attendance**

- [ ] Adam Podolak
- [x] Austin Bennett 
- [ ] Christian Petricca 
- [x] Evan Sturmey
- [ ] Jacob Kish

**Questions to Ask**

- If Deliverable deadlines can be on the friday more frequently to allow more time to implement TA feedback

**Comment by ausbennett** [comment]
Smith advised turning TA feedback into their own issues for traceabililty
