### ISSUE TITLE
TA Request - Contribution Report

### ISSUE THREAD

**Issue by cer-hunter** [ausbennett/mes-finance-platform#47]
Hey all,

Please complete the Contribution report by tomorrow (preferably before like noon). It is important so that we can get an idea of how your group is functioning and what your planning to demo on Wednesday (cause otherwise Dr. Smith and I can only go off of what I know about your group and you won't get the best feedback possible).

Good Luck,
Hunter

**Comment by adampodolak** [comment]
Hey Hunter, 

Sorry about that, the report was completed we just forgot to push the compiled pdf to the main branch.

Thanks,
Adam
